cselab/korali

tutorials/a1-optimization/README.md, tutorials/a2-sampling/README.md, tutorials/a3-bayesian-inference/README.md, tutorials/a4-constrained-optimization/README.md, tutorials/c1-running-cxx/README.md
Many commands in the readme were outdated, for example korali.initialize().
This change has the current code from run-cmaes.py.
Not sure if it should be merged with master or with development
=> Update documentation tutorials a1-a4, add readme to c1

source/modules/problem/bayesian/reference/reference._cpp, source/modules/solver/TMCMC/TMCMC._cpp, source/modules/solver/TMCMC/TMCMC.config, tutorials/basic/3.bayesian.inference/run-mtmcmc.py, tutorials/basic/3.bayesian.inference/run-nested.py, tutorials/basic/3.bayesian.inference/run-tmcmc.py
adding a count for negative definite matrices, fixing the calculation of the FIM, updating tutorial
=> Mtmcmc improvements

docs/web/index.html
adding CSZ lectures, fixing some broken links.
=> Updating webpage

source/engine.cpp, source/engine.hpp, source/modules/solver/CMAES/CMAES.py, source/modules/solver/DEA/DEA.py, source/modules/solver/LMCMAES/LMCMAES.py, source/modules/solver/MCMC/MCMC.py, source/modules/solver/Nested/Nested.py, source/modules/solver/SAEM/SAEM.py, source/modules/solver/TMCMC/TMCMC.py, tools/plotter/__main__.py
- added plotting flag '--all' such that all generations can be plotted for TMCMC
- added logging check if experiment is silent, if its silent no "experiment start/finished" will be printed (request by Lucas)
=> Tmcmc plotter

source/auxiliar/fs.hpp, source/auxiliar/koraliJson.cpp, source/auxiliar/koraliJson.hpp, source/auxiliar/logger.cpp, source/auxiliar/logger.hpp, source/auxiliar/math.cpp, source/auxiliar/math.hpp, source/auxiliar/py2json.hpp, source/engine.cpp, source/engine.hpp, source/korali.hpp, source/modules/problem/gaussian/execute/execute._cpp, source/sample/sample.cpp, source/sample/sample.hpp, tools/dev-tools/correct_style.sh
- close files that were never closed; this fixes a bug that happened when many engines were created in one application.
- fix clang-format maintenance script
=> File error

source/modules/problem/bayesian/reference/reference._cpp, source/modules/solver/TMCMC/TMCMC.py
improved safety of llk calculation in reference._cpp
=> reference safety

docs/manual/using/install.rst
Troubleshooter instructions for setting up mpi4py and Korali in an MPI environment on Piz Daint.
=> Piz Daint instructions

tutorials/basic/3.bayesian.inference/model/model.py
Simplified the model in the Bayesian tutorial.
=> minor change in Bayesian tutorial model

docs/web/index.html
Updated webpage to contain new arxiv paper.
=> updating web with new paper

source/auxiliar/py2json.hpp, source/modules/solver/gaussianProcess/gaussianProcess._cpp
- indent doxygen strings
- fix the verbosity of inner experiment in gaussianProcess.cpp
=> Gp verbosity

examples/.gitignore, install, source/Makefile, source/auxiliar/fs.cpp, source/auxiliar/fs.hpp, source/auxiliar/jsonInterface.cpp, source/auxiliar/jsonInterface.hpp, source/auxiliar/math.cpp, source/modules/conduit/concurrent/concurrent._cpp, source/modules/conduit/conduit._cpp, source/modules/conduit/distributed/distributed._cpp, source/modules/conduit/distributed/distributed._hpp, source/modules/neuralNetwork/neuralNetwork._cpp, source/modules/problem/bayesian/bayesian._cpp, source/modules/problem/bayesian/latent/latent.config, source/modules/problem/bayesian/reference/reference._cpp, source/modules/problem/hierarchical/theta/theta._cpp, source/modules/solver/CMAES/CMAES._cpp, source/modules/solver/LMCMAES/LMCMAES._cpp, source/modules/solver/MCMC/MCMC.config, source/modules/solver/SAEM/SAEM._cpp, source/modules/solver/SAEM/SAEM.config, source/modules/solver/TMCMC/TMCMC._cpp, source/modules/solver/deepLearner/deepLearner._cpp, source/modules/solver/gaussianProcess/gaussianProcess._cpp, source/sample/sample.cpp
=> No warnings2

source/modules/solver/SAEM/README.rst
=> Update README, it sounded a bit sloppy

docker/Dockerfile
RUN git clone https://github.com/cselab/korali.git --recursive --branch master
is using cached data (?)
=> Pull from default branch when building docker image

install
Changes how install checks for openAI-gym
=> python --> python3

source/modules/problem/bayesian/reference/README.rst, source/modules/problem/bayesian/reference/reference._cpp, source/modules/problem/bayesian/reference/reference._hpp, source/modules/problem/bayesian/reference/reference.config, source/modules/solver/sampler/Nested/Nested._cpp
added (positive) student t distribution, and poisson distribution for Bayesian reference problem.
=> Studentdistribution

source/modules/experiment/experiment._cpp, source/modules/experiment/experiment._hpp
I added the random initialization of the seed using nanoseconds since epoch
=> added rnd seed init

source/modules/solver/sampler/Nested/Nested._cpp
this minor fix resolves an overflow I observe some times
=> fix overflow in nested sampler

source/modules/solver/sampler/Nested/Nested._cpp, tests/STAT-005/run-mincmaes1.cpp
undid mistake, from previous merge, hopefully fixed randomly failing test
=> Nested fix evidence

examples/learning/reinforcement/upswing/run-gfpt-double.py, examples/learning/reinforcement/upswing/run-gfpt-single.py, examples/study.cases/microswimmers/run-korali.cpp, source/auxiliar/cbuffer.hpp, source/engine.cpp, source/modules/neuralNetwork/layer/layer._cpp, source/modules/neuralNetwork/layer/layer._hpp, source/modules/neuralNetwork/neuralNetwork._cpp, source/modules/neuralNetwork/neuralNetwork._hpp, source/modules/solver/agent/agent._cpp, source/modules/solver/agent/continuous/DDPG/DDPG._cpp, source/modules/solver/agent/continuous/GFPT/GFPT._cpp, source/modules/solver/agent/continuous/GFPT/GFPT._hpp, source/modules/solver/agent/continuous/cACER/cACER._cpp, source/modules/solver/agent/discrete/DQN/DQN._cpp, source/modules/solver/agent/discrete/dACER/dACER._cpp, source/modules/solver/learner/deepSupervisor/deepSupervisor._cpp
+ Optimized NN hyperparameter management
+ Optimized GFPT to use separate NN for different batch sizes
+ Changes agent to store entire episodes (as opposed to experiences one by one)
=> NN Optimizations and Saving Entire Episode 

examples/study.cases/openAIGym/run-cartpole-dvracer.py, source/build.py, source/engine.cpp, source/modules/experiment/experiment._cpp, source/modules/module.cpp, source/modules/solver/agent/continuous/GFPT/GFPT._cpp, source/modules/solver/learner/deepSupervisor/deepSupervisor._cpp
Hotfix to allow agents to re-run using the learnt policy
=> Agent rerun fix

examples/learning/reinforcement/ABF2D/run-gfpt.py, examples/learning/reinforcement/ABF2D/run-vracer.py, examples/study.cases/ABF3D/_environment/environment.cpp, examples/study.cases/ABF3D/run-gfpt.cpp, source/modules/solver/agent/agent._cpp, source/modules/solver/agent/continuous/GFPT/GFPT._cpp, source/modules/solver/agent/continuous/GFPT/GFPT._hpp, source/modules/solver/agent/continuous/GFPT/GFPT.config, source/modules/solver/agent/continuous/NAF/NAF._cpp, source/modules/solver/agent/continuous/VRACER/VRACER._cpp, source/modules/solver/agent/continuous/continuous._cpp, source/modules/solver/agent/discrete/dVRACER/dVRACER._cpp, tools/rlview/__main__.py
A few improvements to the RL plotter and some of the algos
=> Updating GFPT and plotter

examples/learning/supervised/run-rnn.py, source/modules/solver/learner/deepSupervisor/deepSupervisor._cpp
Fixing a bug that made modify read-only data and thus corrupting results. This manifested on time-dependent problems.
=> Hotfix: RNN working

source/modules/solver/sampler/Nested/Nested._cpp
=> fix nested

examples/study.cases/openAIGym/_jobs/openAIGym_VRACER.sbatch, examples/study.cases/openAIGym/run-vracer.py, tools/rlview/__main__.py
An improved version of RLview:
- Displaying # observations as x-axis
- Added transparency to episode markers 
- Added Zorder to put averages always on top of markers
- Colomap less ugly
=> Fix rl view

examples/study.cases/ABF3D/run-vracer.cpp, examples/study.cases/openAIGym/_model/agent.py, external/install_oneDNN.sh, source/modules/problem/reinforcementLearning/reinforcementLearning._cpp, source/modules/problem/reinforcementLearning/reinforcementLearning.config, source/modules/solver/agent/agent._cpp, source/modules/solver/agent/agent._hpp, source/modules/solver/agent/continuous/VRACER/VRACER._cpp, source/modules/solver/agent/continuous/continuous._cpp, source/modules/solver/agent/continuous/continuous._hpp, source/modules/solver/agent/discrete/discrete._cpp, source/modules/solver/agent/discrete/discrete._hpp, source/modules/solver/learner/deepSupervisor/deepSupervisor._cpp, source/modules/solver/learner/deepSupervisor/deepSupervisor.config, tools/rlview/__main__.py
A collection of optimizations to RL methods
- Using nested openMP parallelism with oneDNN
- Many small fixes to reduce data motion
- Removed by-default agent policy update; it should be explicitly specified if desired
=> RL Optimization

examples/study.cases/openAIGym/_model/agent.py, source/modules/solver/agent/continuous/continuous._cpp
Testing for nans was incorrect and slow, this should be thought of better.
=> Hotfix for bugs in continuous policy

examples/features/checkpoint.resume/run-vracer.py, examples/learning/reinforcement/ABF2D/run-vracer.py, examples/learning/reinforcement/cartpole/.run_test.sh, examples/learning/reinforcement/cartpole/run-dvracer.py, examples/learning/reinforcement/cartpole/run-vracer.py, examples/learning/reinforcement/lander/run-vracer.py, examples/learning/reinforcement/upswing/run-vracer-double.py, examples/learning/reinforcement/upswing/run-vracer-single.py, examples/study.cases/openAIGym/.run_test.sh, examples/study.cases/openAIGym/run-vracer.py, source/modules/solver/agent/agent._cpp, source/modules/solver/agent/agent.config
small fix in testing episode, added missing values which are not assigned when starting from saved results
=> fix testing generation

examples/learning/reinforcement/cartpole/_model/env.py, examples/learning/reinforcement/cartpole/run-vracer.py, source/modules/problem/reinforcementLearning/reinforcementLearning.cpp, source/modules/problem/reinforcementLearning/reinforcementLearning.cpp.base, source/modules/solver/agent/agent.cpp, source/modules/solver/agent/agent.cpp.base
added store episode feature, check cartpole example for usage
=> store episode flag

python/korali/plot/MOCMAES.py
no fix, just a bit of cosmetics
=> remove xticks

examples/study.cases/ABF3D/README.rst
=> update readme abf3d
